name: Cleanup Tests Reports

on:
  schedule:
    - cron: "0 0 * * *" # This will run at 00:00 UTC every day (every 24 hours)

permissions:
  contents: write
  id-token: write
  pull-requests: write
  pages: write
  issues: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Remove test reports
        run: node .github/scripts/cleanup.mjs
