name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  deployments: read
  pull-requests: write
  contents: read
  checks: write
  statuses: write
  issues: write
  actions: write
jobs:
  test-url:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for Vercel Preview Deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 500
    outputs:
      deployment_url: ${{ steps.waitForPreview.outputs.url }}
  test:
    needs: test-url
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
          BASE_URL: ${{ needs.test-url.outputs.deployment_url }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
