name: Playwright Tests
on:
  push:
    branches: [main, dev, stg, prod]
  pull_request:
    branches: [main, dev, stg, prod]

jobs:
  wait-test-url:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
    outputs:
      deployment_url: ${{ steps.waitForPreview.outputs.url }}
  test:
    needs: wait-test-url
    env:
      BASE_URL: ${{ needs.wait-test-url.outputs.deployment_url }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      test_outcome: ${{ steps.test-outcome.outputs.outcome }}
      tests_passed: ${{ steps.collect-test-results.outputs.passed }}
      tests_failed: ${{ steps.collect-test-results.outputs.failed }}
      tests_flaky: ${{ steps.collect-test-results.outputs.flaky }}
      tests_skipped: ${{ steps.collect-test-results.outputs.skipped }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy-report:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Upload Playwright Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
          publish_dir: ./playwright-report
          destination_dir: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      - name: Comment on PR with Playwright Report URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Playwright Test Results
            [View the report here](${{ steps.deploy-report.outputs.html_url }})
            - Tests Passed: ${{ needs.test.outputs.tests_passed }}
            - Tests Failed: ${{ needs.test.outputs.tests_failed }}
            - Tests Flaky: ${{ needs.test.outputs.tests_flaky }}
            - Tests Skipped: ${{ needs.test.outputs.tests_skipped }}
            - Test Outcome: ${{ needs.test.outputs.test_outcome }}
            - Report URL: [Playwright Report](${{ steps.deploy-report.outputs.html_url }})
