name: Playwright Tests
on:
  push:
    branches: [main, dev, stg, prod]
  pull_request:
    branches: [main, dev, stg, prod]

# Adding permissions to allow comment creation
permissions:
  contents: write
  pages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  wait-test-url:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
    outputs:
      deployment_url: ${{ steps.waitForPreview.outputs.url }}
  test:
    needs: wait-test-url
    env:
      BASE_URL: ${{ needs.wait-test-url.outputs.deployment_url }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      test_outcome: ${{ steps.test-outcome.outputs.outcome }}
      tests_passed: ${{ steps.collect-test-results.outputs.passed }}
      tests_failed: ${{ steps.collect-test-results.outputs.failed }}
      tests_flaky: ${{ steps.collect-test-results.outputs.flaky }}
      tests_skipped: ${{ steps.collect-test-results.outputs.skipped }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true
      - name: Collect test results
        id: collect-test-results
        if: always()
        run: |
          if [ -f "playwright-report/test-results.json" ]; then
            # Use jq if available
            if command -v jq >/dev/null 2>&1; then
              PASSED=$(jq '.stats.expected' playwright-report/test-results.json 2>/dev/null || echo 0)
              FAILED=$(jq '.stats.unexpected' playwright-report/test-results.json 2>/dev/null || echo 0)
              FLAKY=$(jq '.stats.flaky' playwright-report/test-results.json 2>/dev/null || echo 0)
              SKIPPED=$(jq '.stats.skipped' playwright-report/test-results.json 2>/dev/null || echo 0)
            else
              # Fallback to grep if jq is not available
              PASSED=$(grep -o '"expected":[0-9]\+' playwright-report/test-results.json | cut -d':' -f2 || echo 0)
              FAILED=$(grep -o '"unexpected":[0-9]\+' playwright-report/test-results.json | cut -d':' -f2 || echo 0)
              FLAKY=$(grep -o '"flaky":[0-9]\+' playwright-report/test-results.json | cut -d':' -f2 || echo 0)
              SKIPPED=$(grep -o '"skipped":[0-9]\+' playwright-report/test-results.json | cut -d':' -f2 || echo 0)
            fi
          else
            PASSED=0
            FAILED=0
            FLAKY=0
            SKIPPED=0
          fi

          echo "passed=${PASSED}" >> $GITHUB_OUTPUT
          echo "failed=${FAILED}" >> $GITHUB_OUTPUT
          echo "flaky=${FLAKY}" >> $GITHUB_OUTPUT
          echo "skipped=${SKIPPED}" >> $GITHUB_OUTPUT
      - name: Set test outcome
        id: test-outcome
        if: always()
        run: echo "outcome=${{ job.status }}" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy:
    needs: test
    if: ${{ always() && needs.test.outputs.test_outcome != 'cancelled' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Playwright Report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: playwright-report
          branch: gh-pages
  comment:
    needs: [test, deploy]
    if: ${{ always() && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repoName = context.repo.repo;
            const owner = context.repo.owner;
            const reportUrl = `https://${owner}.github.io/${repoName}/`;

            // Test summary from outputs
            const testsPassed = '${{ needs.test.outputs.tests_passed || 0 }}';
            const testsFailed = '${{ needs.test.outputs.tests_failed || 0 }}';
            const testsFlaky = '${{ needs.test.outputs.tests_flaky || 0 }}';
            const testsSkipped = '${{ needs.test.outputs.tests_skipped || 0 }}';

            const commentBody = `## Playwright Test Results

            | Status | Count |
            | ------ | ----- |
            | Passed | ${testsPassed} |
            | Failed | ${testsFailed} |
            | Flaky | ${testsFlaky} |
            | Skipped | ${testsSkipped} |

            [View Full Test Report](${reportUrl})
            `;

            // Find existing comment if any
            const issue_number = context.issue.number;
            const { data: comments } = await github.rest.issues.listComments({
              owner,
              repo: repoName,
              issue_number
            });

            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Playwright Test Results');
            });

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner,
                repo: repoName,
                comment_id: botComment.id,
                body: commentBody
              });
              console.log(`Updated comment #${botComment.id}`);
            } else {
              // Create new comment
              const { data: newComment } = await github.rest.issues.createComment({
                owner,
                repo: repoName,
                issue_number,
                body: commentBody
              });
              console.log(`Created comment #${newComment.id}`);
            }

      - name: Create GitHub Actions Summary
        run: |
          REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
          REPORT_URL="https://$REPO_OWNER.github.io/$REPO_NAME/"

          TESTS_PASSED="${{ needs.test.outputs.tests_passed || 0 }}"
          TESTS_FAILED="${{ needs.test.outputs.tests_failed || 0 }}"
          TESTS_FLAKY="${{ needs.test.outputs.tests_flaky || 0 }}"
          TESTS_SKIPPED="${{ needs.test.outputs.tests_skipped || 0 }}"

          echo "## Playwright Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Count |" >> $GITHUB_STEP_SUMMARY
          echo "| ------ | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| Passed | $TESTS_PASSED |" >> $GITHUB_STEP_SUMMARY
          echo "| Failed | $TESTS_FAILED |" >> $GITHUB_STEP_SUMMARY
          echo "| Flaky | $TESTS_FLAKY |" >> $GITHUB_STEP_SUMMARY
          echo "| Skipped | $TESTS_SKIPPED |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[View Full Test Report]($REPORT_URL)" >> $GITHUB_STEP_SUMMARY
